
# Pollution-visualization

This application is a dashboard showing the pollution in the [MASA](https://www.automotivesmartarea.it/?lang=en) sector in Modena.

## Folder scheme

* Data contains all the data that would be generated by PHEMLight called **result_*.csv** and **stream.csv** which is the file that the dashboard would use to display the data.
* Images contains a image generated by mapview.
* R contains r files, dashboard-Modena.r is the dashboard application, and lanzador only rewrites stream.csv data. 

## Requirements

To execute this application is required to have:
* R version 3.6.3
* R package [mapview](https://r-spatial.github.io/mapview/) 2.9.0
* R package [shiny](https://shiny.rstudio.com/) 1.5.0


## Usage

To run the application run the R dashboard-Modena.r script as a background job.

Once the dashboard is running it will show a window with the dashboard, it will show the data saved in stream.csv inside the Data folder 
In order to simulate that the dashboard receives new data by running lanzador.r, this script will rewrite stream.csv periodically, such changes will be detected by the dashboard which will be updated automatically.
